# Generated by Django 2.1.7 on 2019-03-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalrecord',
            old_name='name',
            new_name='exercise',
        ),
    ]
