# Generated by Django 2.1.5 on 2019-02-10 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
